stages:
  - deploy

deploy_to_vm:
  stage: deploy
  image: alpine:latest
  only:
    - main
  before_script:
    - apk add --update openssh rsync
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | base64 -d | ssh-add -
    - mkdir -p ~/.ssh
    - ssh-keyscan $SERVER_IP >> ~/.ssh/known_hosts
  script:
    - rsync -avz --exclude='.git' ./ $SSH_USER@$SERVER_IP:/opt/drp-touchpoint/
    - ssh $SSH_USER@$SERVER_IP "cd /opt/drp-touchpoint && docker-compose down && docker-compose up -d --build"