version: '3.3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    restart: always
    env_file:
      - .env
    volumes:
      - /opt/drp-touchpoint/gcp-credentials.json:/opt/drp-touchpoint/gcp-credentials.json:ro

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:80"
    restart: always